### ISSUE TITLE
Berlin is not recognized.

### ISSUE THREAD

**Issue by aauss** [ecohealthalliance/EpiTator#43]
```python
from epitator.annotator import AnnoDoc
from epitator.geoname_annotator import location_contains
doc = AnnoDoc("Where is Berlin?")
doc.add_tiers(GeonameAnnotator())
annotations = doc.tiers["geonames"]
annotations
```
Outputs:
```python
AnnoTier([])
````
It is not an issue for me, but might be interesting, since it is quite a big city.
Best,
Auss

**Comment by nathanathan** [comment]
Thanks, I'll use this as a test case for future versions of the geoname annotator. Unfortunately this isn't an issue that can be easily fixed by changing a few lines of code. The annotator uses a statistical classifier that would need to be retrained using modified features/parameters/training data in order to prevent this error.
The geoname annotator is designed to perform better on longer documents where contextual features are available. For instance, it should be able to identify Berlin in the sentence, "I am in Germany. Where is Berlin?"
